version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
    restart: always

  dev-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
    restart: always

  prod-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "8080:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
    restart: always
