name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Update homepage in package.json
        run: |
          if [ "$GITHUB_REF" == "refs/heads/dev" ]; then
            NEW_HOMEPAGE="shoplist-dev"
          else
            NEW_HOMEPAGE="shoplist"
          fi
          jq --arg NEW_HOMEPAGE "$NEW_HOMEPAGE" '. + { "homepage": $NEW_HOMEPAGE }' package.json > package.json.tmp
          mv package.json.tmp package.json

      - name: Install Dependencies
        run: npm install

      - name: Build Dev
        if: github.ref == 'refs/heads/dev' || github.event_name == 'pull_request' && github.base_ref == 'refs/heads/dev'
        run: npm run build:dev

      - name: Build Main
        if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request' && github.base_ref == 'refs/heads/main'
        run: npm run build:main

  deploy:
    runs-on: self-hosted

    needs: build

    environment:
      name: dev

    steps:
      - name: Deploy to Dev
        run: ./.github/scripts/deploy.sh dev

  deploy-prod:
    runs-on: self-hosted

    needs: build

    environment:
      name: prod

    steps:
      - name: Deploy to Prod
        run: ./.github/scripts/deploy.sh prod