name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev  
env:
  CI: false
  ENV_TYPE: ${{ github.base_ref == 'refs/heads/dev' || github.ref == 'refs/heads/dev' && 'DEV' || 'PROD' }}
  FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY_${ ENV_TYPE } }}
  FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN_${ ENV_TYPE } }}
  FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL_${ ENV_TYPE } }}
  FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID_${ ENV_TYPE } }}
  FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET_${ ENV_TYPE } }}
  FIREBASE_MESSAGING_SERVER_ID: ${{ secrets.FIREBASE_MESSAGING_SERVER_ID_${ ENV_TYPE } }}
  FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID_${ ENV_TYPE } }}

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Update homepage in package.json
        run: |
          if [ "$GITHUB_REF" == "refs/heads/dev" ]; then
            NEW_HOMEPAGE="shoplist-dev"
          else
            NEW_HOMEPAGE="shoplist"
          fi
          jq --arg NEW_HOMEPAGE "$NEW_HOMEPAGE" '. + { "homepage": $NEW_HOMEPAGE }' package.json > package.json.tmp
          mv package.json.tmp package.json

      - name: Install Dependencies
        run: npm install
        
      - name: Build Dev     
        if: github.ref == 'refs/heads/dev' || github.event_name == 'pull_request' && github.base_ref == 'refs/heads/dev'
        run: npm run build
        
      - name: Build Prod   
        if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request' && github.base_ref == 'refs/heads/main'
        run: npm run build

  deploy-dev:
    runs-on: self-hosted
    needs: build
    if: github.ref == 'refs/heads/dev' || github.event_name == 'pull_request' && github.base_ref == 'refs/heads/dev'
    steps:
      - name: Deploy to Dev
        run: ./.github/scripts/deploy.sh dev

  deploy-prod:
    runs-on: self-hosted
    needs: build
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request' && github.base_ref == 'refs/heads/main'
    steps:
      - name: Deploy to Prod
        run: ./.github/scripts/deploy.sh prod
